version: '3'

services:
  locus-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/locus-cpython:1.3.0
    volumes:
      - ./locus:/opt/locus/locus
      - ./pytest.ini:/opt/locus/pytest.ini
      - ./README.md:/opt/locus/README.md
      - ./requirements-tests.txt:/opt/locus/requirements-tests.txt
      - ./requirements.txt:/opt/locus/requirements.txt
      - ./setup.py:/opt/locus/setup.py
      - ./tests:/opt/locus/tests
    entrypoint: pytest
