version: '3'

services:
  locus-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/locus-cpython:10.0.0-alpha
    volumes:
      - ./locus:/opt/locus/locus
      - ./pyproject.toml:/opt/locus/pyproject.toml
      - ./README.md:/opt/locus/README.md
      - ./setup.py:/opt/locus/setup.py
      - ./tests:/opt/locus/tests
    entrypoint: pytest
