version: '3'

services:
  locus-cpython:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/locus-cpython:0.6.1
    volumes:
      - ./locus/:/opt/locus/locus/
      - ./tests/:/opt/locus/tests/
      - ./README.md:/opt/locus/README.md
      - ./requirements.txt:/opt/locus/requirements.txt
      - ./requirements-tests.txt:/opt/locus/requirements-tests.txt
      - ./setup.py:/opt/locus/setup.py
      - ./pytest.ini:/opt/locus/pytest.ini
    entrypoint: pytest
